info:
  version: 0.0.1
  title: The monbus rest-api with serverless pattern
x-project-name: monbus-restapi
paths:
  /timetables:
    get:
      responses:
        "200":
          description: Success
      parameters: []
  /events/stations-sync:
    put:
      description: Run on scheduled event for stations synchronization
      responses:
        "200":
          description: Success
      parameters: []
  "/stations/{id}":
    post:
      tags:
        - Stations Service Group
      description: Watch a realtime bus stop by StationId
      operationId: fetchTimeByStation
      parameters:
        - in: path
          name: id
          required: true
          type: string
        - description: Send my location information
          required: true
          name: body
          in: body
          schema:
            type: object
            properties:
              lat:
                type: number
              long:
                type: number
      responses:
        "200":
          description: Success
      consumes:
        - application/json
  /stations:
    get:
      tags:
        - Stations Service Group
      description: Get Stations Information
      operationId: getStations
      responses:
        "200":
          description: Success
      parameters: []
  /hystrix.stream:
    get:
      description: hystrix server-sent event stream
      responses:
        "200":
          description: hystrix server-sent event response
          schema:
            type: object
      parameters: []
      produces:
        - text/event-stream
x-project-id: 32747471
swagger: "2.0"
